### PR TITLE
#Issue-8 Revise dryville_story.md

### PR DESCRIPTION
**Pull request by shamshaw**
Add two new sections to the dryville_story.md that were pulled from [here](https://www.usgs.gov/special-topic/water-science-school/science/story-water-dryville?qt-science_center_objects=0#qt-science_center_objects)

### CODE REVIEW

**Review by lindsayplatt — APPROVED** [review]
Nice 🎉

When the issue said,

> In your description, make sure to reference this issue by typing #[issue number].

it meant that in your PR description, you could write something like this:

> This addresses #8 

When you type the `#` symbol in GitHub, it will automatically start populating the potential issue numbers you are referencing. By using this syntax somewhere in your comments or description, it will create an actual link between the two (Now that I have tagged it, if you go to issue 8, you should see a link to this PR. So use `#` and then immediately follow it with a number to reference a specific issue or PR.

**Comment by lindsayplatt** [comment]
Correction to the above ... I think I need to mention the issue without having it in the quoted syntax for it to work. Trying it here by tagging it one more time. See issue #8

**Comment by lindsayplatt** [comment]
Yep, that worked. Now issue 8, has this:

image

**Comment by lindsayplatt** [comment]
No need to change anything. Just wanted to make those notes here before you moved on. I am merging this now so that you can continue, but let me know if you have questions about this!

**Comment by shamshaw** [comment]
Ah - this makes sense. I think I read that and thought it was just meaning to mention the issue in the title or description. Makes more sense that you can actually link a PR to an issue. :+1:

**Pull request merged**
